#Controller 
From ubuntu

RUN apt-get update -y
RUN bash -c 'apt-get install -y python-{colorama,dev,eventlet,lxml,msgpack,netaddr,networkx,oslo.config,paramiko,routes,six,webob,influxdb}'

#controller
RUN apt-get update ; apt-get install -y python3-pip python3-setuptools
RUN pip3 install --upgrade pip
RUN pip3 install ryu influxdb tox

WORKDIR /influxdb
ENTRYPOINT ["/bin/bash"]

