#Switch

FROM ubuntu:latest

RUN apt-get update && apt-get install -y openvswitch-switch

# Install Python packages
RUN bash -c 'apt-get install -y python-{colorama,dev,eventlet,lxml,msgpack,netaddr,networkx,oslo.config,paramiko,pip,routes,six,webob,influxdb}'

# Install Ryu
RUN pip install ryu

# Install pipework
RUN apt-get install -y arping
RUN wget --no-check-certificate --quiet https://raw.githubusercontent.com/jpetazzo/pipework/master/pipework -O /usr/local/bin/pipework
RUN chmod +x /usr/local/bin/pipework

# Install misc useful stuffs
RUN apt-get install -y less lv netcat telnet bash-completion vim byobu

# Install init
# ADD ./init.dind-ovs-ryu.sh /init.dind-ovs-ryu.sh
# RUN chmod +x /init.dind-ovs-ryu.sh
# CMD ["wrapdocker", "/init.dind-ovs-ryu.sh"]

#controller
RUN apt-get update ; apt-get install -y python3-pip python3-setuptools
RUN pip3 install --upgrade pip
RUN pip3 install ryu influxdb tox

ENV HOME /root
WORKDIR /root
CMD ["bash"]
